In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
vinos = pd.read_csv("archives/vino.csv")

In [5]:
vinos.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [7]:
vinos["Wine Type"].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [8]:
vinos["Wine Type"].value_counts()

Two      71
One      59
Three    48
Name: Wine Type, dtype: int64

In [9]:
y = vinos['Wine Type']
X = vinos.drop('Wine Type', axis=1)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
arbol = DecisionTreeClassifier()

In [14]:
arbol.fit(X_train, y_train)

DecisionTreeClassifier()

In [16]:
predicciones = arbol.predict(X_test)
predicciones

array(['Two', 'Two', 'Two', 'One', 'One', 'Three', 'Three', 'Three',
       'Two', 'Three', 'Three', 'Two', 'Two', 'One', 'One', 'One',
       'Three', 'Three', 'One', 'Three', 'Three', 'Two', 'Three', 'Three',
       'Three', 'Two', 'Two', 'One', 'Two', 'Two', 'Two', 'Two', 'One',
       'Two', 'Three', 'Three', 'One', 'One', 'One', 'Two', 'Two', 'Two',
       'One', 'Two', 'Three', 'Three', 'One', 'One', 'Two', 'Three',
       'Two', 'One', 'Three', 'Two'], dtype=object)

In [17]:
np.array(y_test)

array(['Two', 'Two', 'Two', 'One', 'One', 'Three', 'Two', 'Three', 'Two',
       'Three', 'Three', 'Two', 'One', 'One', 'One', 'One', 'Three',
       'Three', 'One', 'Three', 'Three', 'Two', 'Three', 'Three', 'Three',
       'Two', 'One', 'One', 'Two', 'Two', 'Two', 'Two', 'One', 'Two',
       'Three', 'Three', 'One', 'One', 'One', 'Three', 'Two', 'Two',
       'One', 'Two', 'Three', 'Three', 'One', 'One', 'Two', 'Three',
       'Two', 'Two', 'Three', 'Two'], dtype=object)

In [19]:
from sklearn.metrics import classification_report, confusion_matrix

In [20]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       0.93      0.88      0.90        16
       Three       0.94      0.94      0.94        18
         Two       0.86      0.90      0.88        20

    accuracy                           0.91        54
   macro avg       0.91      0.91      0.91        54
weighted avg       0.91      0.91      0.91        54



In [21]:
print(confusion_matrix(y_test, predicciones))

[[14  0  2]
 [ 0 17  1]
 [ 1  1 18]]
