In [2]:
import pandas as pd
import numpy as np

In [4]:
ventas_enero = np.random.randint(100,500,3)
ventas_enero

array([130, 488, 140])

In [6]:
ventas_febrero = np.random.randint(100,500,3)
ventas_febrero

array([353, 209, 323])

In [7]:
ventas_marzo = np.random.randint(100,500,3)
ventas_marzo

array([113, 450, 374])

In [8]:
filas = ["ventas_enero", "ventas_febrero", "ventas_marzo"]
filas

['ventas_enero', 'ventas_febrero', 'ventas_marzo']

In [9]:
columnas = ["oficina_1", "oficina_2", "oficina_3"]
columnas

['oficina_1', 'oficina_2', 'oficina_3']

In [10]:
ventas = [ventas_enero, ventas_febrero, ventas_marzo]
ventas

[array([130, 488, 140]), array([353, 209, 323]), array([113, 450, 374])]

In [11]:
dataframe = pd.DataFrame(ventas, filas, columnas)
dataframe

oficina_1  oficina_2  oficina_3
ventas_enero          130        488        140
ventas_febrero        353        209        323
ventas_marzo          113        450        374

In [13]:
ventas_enero_oficina_1 = dataframe["oficina_1"]["ventas_enero"]

In [14]:
print("Las ventas de enero de la oficina 1 son {}".format(ventas_enero_oficina_1))

Las ventas de enero de la oficina 1 son 130
