In [1]:
import numpy as np

In [3]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [7]:
array + 40

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [8]:
array - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [11]:
array2 = np.arange(5,15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [13]:
array2 * array

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [14]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [15]:
np.max(array)

9

In [17]:
np.min(array)

0