In [1]:
import numpy as np

In [2]:
array = np.arange(0,9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
array[0]

0

In [4]:
array[1]

1

In [5]:
array[-1]

8

In [6]:
array[2:4]

array([2, 3])

In [7]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
array[5:]

array([5, 6, 7, 8])

In [9]:
array[:4]

array([0, 1, 2, 3])

In [11]:
array2 = array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])