In [1]:
import numpy as np

In [3]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
array[0]

array([1, 2, 3])

In [6]:
array2 = array[:2]
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
array[0][0]

1

In [8]:
array[0,0]

1

In [11]:
array[1,1]

5

In [12]:
array[:,0]

array([1, 4, 7])

In [13]:
array[:,1]

array([2, 5, 8])

In [18]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])