In [1]:
import numpy as np

In [2]:
np.random.rand(5)

array([0.40456801, 0.67936758, 0.93749084, 0.76133259, 0.9845204 ])

In [3]:
np.random.rand(2,3)

array([[0.52279343, 0.29665188, 0.35909081],
       [0.49111074, 0.52238599, 0.04649749]])

In [4]:
np.random.randn(4)

array([-0.99934547,  2.27719646,  0.1570103 , -0.50421445])

In [5]:
np.random.randn(4,5)

array([[ 0.06013854,  0.06822206, -0.3624015 ,  1.75907522,  1.53461645],
       [-0.80252581, -0.68487757, -1.03518898,  0.33454327,  1.10375335],
       [-1.06943479,  0.99622711, -2.3010971 , -0.11888918,  1.12991865],
       [-0.5264868 ,  1.09715573, -1.34993963, -0.62601525,  0.13872056]])